---

- name: Install influxdb
  package:
    name: "{{ packages_influxdb }}"
    state: present
  tags: ['influxdb']

- name: Ensure influxdb is configured
  template:
    src: influxdb_config.toml.j2
    dest: /etc/influxdb/config.toml
    owner: root
    group: influxdb
    mode: 0640
  tags: ['influxdb']
  notify: restart influxdb

- name: Ensure influxdb is enabled
  systemd:
    name: influxdb
    state: started
    enabled: true
  tags: ['influxdb']

- name: Ensure influxdb firewall port is open
  firewalld:
    zone: "{{ firewall_zone }}"
    port: "{{influxdb_port}}/tcp"
    permanent: true
    state: enabled
  when: config_firewall and open_influxdb_port
  notify: reload firewalld
  tags: ['influxdb', 'firewalld']

- name: Ensure collectd firewall port is open
  firewalld:
    zone: "{{ firewall_zone }}"
    port: "{{influxdb_collectd_port}}/udp"
    permanent: true
    state: enabled
  when: config_firewall and influxdb_collectd and open_collectd_port
  notify: reload firewalld
  tags: ['influxdb', 'firewalld']
