---
# tasks file for geekoops-grafana

# Distribution specific vars are ALWAYS needed, so don't forget the tags here
- name: include distribution specific vars
  include_vars: "{{ansible_distribution}}_{{ansible_distribution_version}}.yml"
  tags: ['grafana']
  
- include: influxdb.yml
  when: influxdb == true
- include: grafana.yml
